---
title: "Final model"
author: "Pascal Jerney"
date: "2021-05-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, echo=FALSE}

if (!require("pacman", quietly = TRUE)) {
  install.packages("pacman")
}
pacman::p_load("conflicted")

# Resolve function conflicts before loading other packages
conflict_prefer("select", "dplyr", quiet = TRUE)
conflict_prefer("filter", "dplyr", quiet = TRUE)
conflict_prefer("collapse", "dplyr", quiet = TRUE)

pacman::p_load(
  "tidyverse",
  "fs",
  "glue",
  "nlme",
  "MuMIn",
  "data.table",
  "tidybayes"
)

# I prefer to view outputs in non-scientific notation
options(scipen = 6, digits = 4)

prepender <- function(string, prefix = "PID", sep = ": ") {
  paste0(prefix, sep, string)
}

```

```{r load_data, include=FALSE}

one_over_mac_filtered <-
  read_rds(file = path_wd("output", "one_over_mac_filtered", ext = "rds"))

resamples <-
  read_rds(file = path_wd("output", "resamples", ext = "rds"))

```

## Introduction

For the final model, we chose the model with `ce_mac` as fixed effect, `pid` as
random intercept, `ce_mac:pid` as random slope, continuous AR1 error structure
within `pid` and `log(peak_alpha)` as outcome.

```{r load_mixed_intercept_slope_car1_model, include=FALSE}

model5_specs <-
  read_rds(file = path_wd("output", "model5_specs", ext = "rds"))

```

## Model predictions

### Population

```{r predictions_population}

# unique(resamples[, rbindlist(resample, idcol = "seed")][, .(pid, ce_mac_pid_mean)], by = c("pid"))

setDF(model5_specs[, rbindlist(predict, idcol = "seed")
][unique(resamples[, rbindlist(resample, idcol = "seed")][, .(pid, ce_mac_pid_mean)], by = c("pid")), on = "pid"][, .(seed, pid, ce_mac = ce_mac_pid_centered + ce_mac_pid_mean, predict = exp(predict))]) %>%
    as_tibble() %>%
    group_by(pid, ce_mac) %>%
    mean_qi(predict, .width = c(0.95)) %>%
    ggplot(aes(x = ce_mac, y = predict, group = pid)) +
    geom_path(alpha = 0.25) +
    labs(title = "Model predictions for population",
         subtitle = "Original scale",
         x = "ceMAC",
         y = "Predicted peak alpha")

setDF(model5_specs[, rbindlist(predict, idcol = "seed")
][, .(seed, pid, ce_mac_pid_centered,
      predict = exp(predict))]) %>%
    as_tibble() %>%
    group_by(pid, ce_mac_pid_centered) %>%
    mean_qi(predict, .width = c(0.95)) %>%
  ggplot(aes(x = ce_mac_pid_centered, y = predict, group = pid)) +
  geom_path(alpha = 0.25) +
  labs(title = "Model predictions for population",
       subtitle = "Centered scale",
       x = "Within-group centered ceMAC",
       y = "Predicted peak alpha")

```

### Patient-wise

```{r predictions_pid, fig.height=200, out.width="100%"}

setDF(model5_specs[, rbindlist(predict, idcol = "seed")
                   ][, .(seed, pid, ce_mac_pid_centered,
                         predict = exp(predict))]) %>%
  as_tibble() %>%
  group_by(pid, ce_mac_pid_centered) %>%
  mean_qi(predict, .width = c(0.5, 0.8, 0.95)) %>%
  ggplot(aes(x = ce_mac_pid_centered, y = predict, group = pid)) +
  geom_point(
    aes(x = ce_mac_pid_centered, y = peak_alpha),
    data = one_over_mac_filtered[, slice_sample(.SD, n = 100), by = pid],
    size = 0.5, alpha = 0.25) +
  tidybayes::geom_lineribbon(aes(ymin = .lower, ymax = .upper), alpha = 0.5,
                             size = 0.5) +
  facet_wrap(vars(pid), ncol = 3, scales = "fixed",
             labeller = as_labeller(prepender)) +
  labs(title = "Model predictions per patient",
       x = "Within-group centered ceMAC",
       y = "Predicted peak alpha",
       fill = "Confidence interval") +
  theme(legend.position="top")

```
