---
title: "Modelling"
author: "Pascal Jerney"
date: "2021-03-08"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, echo=FALSE}

if (!require("pacman", quietly = TRUE)) {
  install.packages("pacman")
}
pacman::p_load(
  "tidyverse",
  "conflicted",
  "fs",
  "glue",
  "nlme",
  "broom.mixed"
)

source(path_wd("code", "groupwise_resampling", ext = "R"))

conflict_prefer("select", "dplyr", quiet = TRUE)
conflict_prefer("filter", "dplyr", quiet = TRUE)
conflict_prefer("collapse", "dplyr", quiet = TRUE)

options(scipen = 6, digits = 4) # I prefer to view outputs in non-scientific notation

one_over_mac_filtered <-
  read_rds(file = path_wd("output", "one_over_mac_filtered", ext = "rds"))

# models <-
#   resamples %>%
#   mutate(model0 = map(data, function(df) gls(log(peak_alpha) ~ 1, data = df, method = "ML"))) %>%
#   mutate(model1 = map(data, function(df) gls(log(peak_alpha) ~ ce_mac, data = df, method = "ML"))) %>%
#   mutate(model2 = map(data, function(df) lme(log(peak_alpha) ~ ce_mac, data = df, random = ~ 1 | pid, method = "ML"))) %>%
#   mutate(model3 = map(data, function(df) lme(log(peak_alpha) ~ ce_mac, data = df, random = ~ ce_mac | pid, method = "ML")))
#   mutate(model4 = map(data, function(df) lme(log(peak_alpha) ~ ce_mac, data = tibble.1overmac_train, random = ~ ce_mac | pid, correlation = corAR1(), method = "ML")))
#   mutate(model5 = map(data, function(df) lme(log(peak_alpha) ~ ce_mac, data = tibble.1overmac_train, random = ~ ce_mac | pid, correlation = corAR1(form = ~ 1 | pid), method = "ML")))
#   mutate(model6 = map(data, function(df) lme(log(peak_alpha) ~ ce_mac, data = tibble.1overmac_train, random = ~ ce_mac | pid, correlation = corAR1(form = ~ time | pid), method = "ML")))
#   mutate(model7 = map(data, function(df) lme(log(peak_alpha) ~ ce_mac, data = tibble.1overmac_train, random = ~ ce_mac | pid, correlation = corARMA(form = ~ time | pid, p = 1, q = 1), method = "ML")))

```

## Introduction

Data is resampled groupwise over `pid`, with 1% of the data each and repeated
100 times. This will be increased in the future.

```{r introduction}

resamples <-
  resample_groupwise(one_over_mac_filtered,
                     pid,
                     prop = 0.01,
                     times = 100) %>%
  mutate(data = map(data, ~ arrange(.x, pid, time)))

```

## Modelling

### Null model

Intercept-only model with `log(peak_alpha)` as outcome.

```{r null_model}

models <-
  resamples %>%
  mutate(model0 = map(data, function(df)
    gls(
      log(peak_alpha) ~ 1, data = df, method = "ML"
    ))) %>%
  mutate(model0_tidy = map(model0, 
                           ~ broom.mixed::tidy(., exponentiate = TRUE))) %>%
  mutate(model0_criteria = map(model0, ~ tibble(aic = AIC(.x))))

models %>%
  unnest(model0_tidy, names_sep = "_") %>%
  group_by(model0_tidy_term) %>%
  mutate(across(model0_tidy_estimate, 
                list(mean = mean, median = median))) %>%
  ggplot(aes(x = model0_tidy_estimate)) +
  facet_wrap(vars(model0_tidy_term), scales = "free") +
  geom_histogram(aes(y = ..density..), position = "identity", bins = 15) +
  geom_density() +
  geom_vline(aes(xintercept = model0_tidy_estimate_mean),
             colour = "red",
             linetype = "dashed") +
  geom_vline(aes(xintercept = model0_tidy_estimate_median),
             colour = "blue",
             linetype = "dashed") +
  labs(
    title = "Bootstrapped estimate plot",
    subtitle = "Mean in red, median in blue",
    x = "Estimate",
    y = "Density"
  )

```

#### Summary

```{r null_model_summary}

models %>%
  unnest(model0_tidy, names_sep = "_") %>%
  unnest(model0_criteria, names_sep = "_") %>%
  group_by(model0_tidy_term) %>%
  summarise(across(c(contains("estimate"), 
                     contains("p.value"), 
                     contains("aic")), 
                   list(mean = mean, se = ~ sd(.x) / sqrt(n())))) %>%
  pivot_longer(cols = c(everything(), -contains("term")),
               names_to = c("Bootstrap estimate", "Statistic"),
               names_prefix = "model0_", names_pattern = "(?:tidy_|criteria_)?(.*)_(.*)$",
               values_to = "Value") %>%
  rename("Term" = model0_tidy_term) %>%
  knitr::kable(digits = 10)

```

### Model with ce_mac as fixed effect

Model with `ce_mac` as fixed effect and `log(peak_alpha)` as outcome.

```{r linear_model}

models <-
  models %>%
  mutate(model1 = map(data, function(df)
    gls(
      log(peak_alpha) ~ ce_mac, data = df, method = "ML"
    ))) %>%
  mutate(model1_tidy = map(model1, 
                           ~ broom.mixed::tidy(., exponentiate = TRUE))) %>%
  mutate(model1_criteria = map(model1, ~ tibble(aic = AIC(.x))))

models %>%
  unnest(model1_tidy, names_sep = "_") %>%
  group_by(model1_tidy_term) %>%
  mutate(across(model1_tidy_estimate, 
                list(mean = mean, median = median))) %>%
  ggplot(aes(x = model1_tidy_estimate)) +
  facet_wrap(vars(model1_tidy_term), scales = "free") +
  geom_histogram(aes(y = ..density..), position = "identity", bins = 15) +
  geom_density() +
  geom_vline(aes(xintercept = model1_tidy_estimate_mean),
             colour = "red",
             linetype = "dashed") +
  geom_vline(aes(xintercept = model1_tidy_estimate_median),
             colour = "blue",
             linetype = "dashed") +
  labs(
    title = "Bootstrapped estimate plot",
    subtitle = "Mean in red, median in blue",
    x = "Estimate",
    y = "Density"
  )

```

#### Summary

```{r linear_model_summary}

models %>%
  unnest(model1_tidy, names_sep = "_") %>%
  unnest(model1_criteria, names_sep = "_") %>%
  group_by(model1_tidy_term) %>%
  summarise(across(c(contains("estimate"), 
                     contains("p.value"), 
                     contains("aic")), 
                   list(mean = mean, se = ~ sd(.x) / sqrt(n())))) %>%
  pivot_longer(cols = c(everything(), -contains("term")),
               names_to = c("Bootstrap estimate", "Statistic"),
               names_prefix = "model1_", names_pattern = "(?:tidy_|criteria_)?(.*)_(.*)$",
               values_to = "Value") %>%
  rename("Term" = model1_tidy_term) %>%
  knitr::kable(digits = 10)

```
